pipeline {
    agent any

    environment {
        ARM_SUBSCRIPTION_ID = credentials('6babc3f8-793c-4200-9aa3-51e8d33ff572')
        ARM_CLIENT_ID       = credentials('c421e394-9c7d-43f8-9b93-76ea734b2afb')
        ARM_CLIENT_SECRET   = credentials('vD18Q~yQD-6QLeTvTNP5Kh9-BSdElQpEPCdD6anY')
        ARM_TENANT_ID       = credentials('7597b8dc-1559-4285-901d-856b7ac20009')
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/prashanth3516/Terraform-repo.git'
            }
        }

        stage('Terraform Init') {
            steps {
                sh 'terraform init'
            }
        }

        stage('Terraform Plan') {
            steps {
                sh '''
                terraform plan \
                  -var subscription_id=$ARM_SUBSCRIPTION_ID \
                  -var client_id=$ARM_CLIENT_ID \
                  -var client_secret=$ARM_CLIENT_SECRET \
                  -var tenant_id=$ARM_TENANT_ID
                '''
            }
        }

        stage('Terraform Apply') {
            steps {
                sh '''
                terraform apply -auto-approve \
                  -var subscription_id=$ARM_SUBSCRIPTION_ID \
                  -var client_id=$ARM_CLIENT_ID \
                  -var client_secret=$ARM_CLIENT_SECRET \
                  -var tenant_id=$ARM_TENANT_ID
                '''
            }
        }
    }
}
